version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=dev-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - dev-net
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.7.0
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - dev-net
  db-api:
    image: clojure:lein-2.8.3
    ports:
      - 80:8080
    networks:
      - dev-net
    entrypoint:
      - java
      - -jar
      - /app/db-api/target/db-api-0.1.0-standalone.jar
    volumes:
      - type: bind
        source: ../../
        target: /app

volumes:
  esdata:
    driver: local

networks:
  dev-net:
